package handlers

import (
	"sort"
	"testing"
	"testing/quick"
)

// Feature: marketplace-improvements, Property 7: Top Companies ordering is
// monotonic in rank score.
//
// These tests exercise the pure ranking core rankTopCompanies, which mirrors the
// scored ORDER BY inside GetTopCompanies' SQL. Because the ordering logic is
// pure, the properties below can be validated across many randomized company
// sets without a database.

// boundedReviews maps an arbitrary int generated by testing/quick into a
// bounded, non-negative positive-review count. Bounding keeps generated
// distributions in a realistic space (0..199) while still spanning ties and a
// wide spread of scores. The upper bound stays well under rankWeightHistory
// (1000) so the prior-order signal genuinely dominates, matching the SQL.
func boundedReviews(n int) int {
	if n < 0 {
		n = -n
	}
	return n % 200 // 0..199
}

// genCompanies builds a deterministic-from-input slice of companyRank values out
// of the raw arbitrary slices testing/quick provides, so each generated case is
// a well-formed set of companies.
func genCompanies(reviews []int, priors, subs []bool) []companyRank {
	n := len(reviews)
	if len(priors) < n {
		n = len(priors)
	}
	if len(subs) < n {
		n = len(subs)
	}
	out := make([]companyRank, n)
	for i := 0; i < n; i++ {
		out[i] = companyRank{
			id:              int64(i + 1),
			positiveReviews: boundedReviews(reviews[i]),
			hasPriorOrder:   priors[i],
			isSubscribed:    subs[i],
		}
	}
	return out
}

// TestProperty7_RankingMonotonic is the core property test.
//
// Feature: marketplace-improvements, Property 7: Top Companies ordering is
// monotonic in rank score.
//
// Validates: Requirements 8.1, 8.2, 8.3.
//
// For any set of companies, rankTopCompanies produces an order that is sorted
// non-increasingly by rank score (prior-order weight plus positive-review
// count), and the result is a permutation of the input (nothing lost or
// duplicated).
func TestProperty7_RankingMonotonic(t *testing.T) {
	property := func(reviews []int, priors, subs []bool) bool {
		in := genCompanies(reviews, priors, subs)
		out := rankTopCompanies(in)

		// 1. Same multiset of companies (lossless permutation).
		if len(out) != len(in) {
			t.Logf("length changed: in=%d out=%d", len(in), len(out))
			return false
		}
		if !sameMultiset(in, out) {
			t.Logf("output is not a permutation of input")
			return false
		}

		// 2. Non-increasing by score across adjacent pairs.
		for i := 1; i < len(out); i++ {
			if rankScore(out[i-1]) < rankScore(out[i]) {
				t.Logf("not monotonic at %d: %d < %d", i,
					rankScore(out[i-1]), rankScore(out[i]))
				return false
			}
		}
		return true
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 500}); err != nil {
		t.Errorf("Property 7 (monotonic ranking) failed: %v", err)
	}
}

// TestProperty7_PriorOrderOutranksEqual asserts the specific clause of Property
// 7: a company the user has ordered from outranks an otherwise-equal company
// they have not.
//
// Validates: Requirements 8.2, 8.3.
//
// For any positive-review count shared by two companies, the one with
// hasPriorOrder=true must appear before the one with hasPriorOrder=false in the
// ranked output.
func TestProperty7_PriorOrderOutranksEqual(t *testing.T) {
	property := func(reviews int) bool {
		r := boundedReviews(reviews)
		withPrior := companyRank{id: 1, positiveReviews: r, hasPriorOrder: true}
		withoutPrior := companyRank{id: 2, positiveReviews: r, hasPriorOrder: false}

		out := rankTopCompanies([]companyRank{withoutPrior, withPrior})
		// The prior-order company (id 1) must come first.
		return out[0].id == 1 && out[1].id == 2
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 200}); err != nil {
		t.Errorf("prior-order-outranks-equal property failed: %v", err)
	}
}

// sameMultiset reports whether a and b contain the same companyRank values
// regardless of order. Companies are compared by their full content so a lost,
// duplicated, or mutated entry is detected.
func sameMultiset(a, b []companyRank) bool {
	if len(a) != len(b) {
		return false
	}
	key := func(c companyRank) [4]int {
		prior, sub := 0, 0
		if c.hasPriorOrder {
			prior = 1
		}
		if c.isSubscribed {
			sub = 1
		}
		return [4]int{int(c.id), c.positiveReviews, prior, sub}
	}
	ka := make([][4]int, len(a))
	kb := make([][4]int, len(b))
	for i := range a {
		ka[i] = key(a[i])
	}
	for i := range b {
		kb[i] = key(b[i])
	}
	less := func(s [][4]int) func(i, j int) bool {
		return func(i, j int) bool {
			for k := 0; k < 4; k++ {
				if s[i][k] != s[j][k] {
					return s[i][k] < s[j][k]
				}
			}
			return false
		}
	}
	sort.SliceStable(ka, less(ka))
	sort.SliceStable(kb, less(kb))
	for i := range ka {
		if ka[i] != kb[i] {
			return false
		}
	}
	return true
}

// TestRankTopCompanies_Examples documents concrete ordering cases that pin the
// scoring boundaries, complementing the randomized properties above.
func TestRankTopCompanies_Examples(t *testing.T) {
	in := []companyRank{
		{id: 1, positiveReviews: 50, hasPriorOrder: false},
		{id: 2, positiveReviews: 0, hasPriorOrder: true},    // score 1000
		{id: 3, positiveReviews: 200, hasPriorOrder: false}, // score 200
		{id: 4, positiveReviews: 10, hasPriorOrder: true},   // score 1010
	}
	out := rankTopCompanies(in)
	wantOrder := []int64{4, 2, 3, 1} // 1010, 1000, 200, 50
	for i, want := range wantOrder {
		if out[i].id != want {
			t.Errorf("position %d: got id=%d, want id=%d (scores: %v)",
				i, out[i].id, want, scoresOf(out))
			break
		}
	}

	// Input must not be mutated by ranking.
	if in[0].id != 1 || in[1].id != 2 || in[2].id != 3 || in[3].id != 4 {
		t.Errorf("rankTopCompanies mutated its input slice: %v", in)
	}
}

func scoresOf(cs []companyRank) []int {
	s := make([]int, len(cs))
	for i, c := range cs {
		s[i] = rankScore(c)
	}
	return s
}
