package handlers

import (
	"testing"
	"testing/quick"
)

// Feature: marketplace-improvements, Property 13: Photo limits are enforced and
// over-limit additions are rejected without writing.
//
// These tests exercise the pure decision core checkPhotoLimits, which the
// DB-backed validatePhotoLimits delegates to. Because the decision logic is pure,
// the property below can be validated across many randomized photo distributions
// without a database.

// nonNeg maps an arbitrary int generated by testing/quick into a bounded,
// non-negative count. Bounding keeps the generated distributions in a realistic
// space (0..40 per dimension) so the property meaningfully exercises both the
// accept and reject sides of each cap.
func nonNeg(n int) int {
	if n < 0 {
		n = -n
	}
	return n % 41 // 0..40
}

// TestProperty13_PhotoLimitsEnforced is the core property test.
//
// Feature: marketplace-improvements, Property 13: Photo limits are enforced and
// over-limit additions are rejected without writing.
//
// Validates: Requirements 12.1, 12.3, 12.5, 12.6.
//
// For random photo distributions and incoming counts, an addition is accepted IFF
// it keeps the target variant ≤ maxVariantPhotos (4) AND the product total
// ≤ maxProductPhotos (20); equivalently, a rejection corresponds exactly to a
// limit violation.
func TestProperty13_PhotoLimitsEnforced(t *testing.T) {
	property := func(cv, ds, ov, inc int) bool {
		currentVariantPhotos := nonNeg(cv)
		defaultSetCount := nonNeg(ds)
		otherVariantsTotal := nonNeg(ov)
		incoming := nonNeg(inc)

		err := checkPhotoLimits(currentVariantPhotos, defaultSetCount, otherVariantsTotal, incoming)

		variantOK := currentVariantPhotos+incoming <= maxVariantPhotos
		productTotalAfter := defaultSetCount + otherVariantsTotal + currentVariantPhotos + incoming
		productOK := productTotalAfter <= maxProductPhotos
		shouldAccept := variantOK && productOK

		accepted := err == nil

		// Accept IFF within both caps.
		if accepted != shouldAccept {
			t.Logf("mismatch: cv=%d ds=%d ov=%d inc=%d variantOK=%v productOK=%v accepted=%v err=%v",
				currentVariantPhotos, defaultSetCount, otherVariantsTotal, incoming,
				variantOK, productOK, accepted, err)
			return false
		}

		// A rejection must correspond to an actual limit violation.
		if !accepted && variantOK && productOK {
			t.Logf("spurious rejection: cv=%d ds=%d ov=%d inc=%d err=%v",
				currentVariantPhotos, defaultSetCount, otherVariantsTotal, incoming, err)
			return false
		}

		return true
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 1000}); err != nil {
		t.Errorf("Property 13 failed: %v", err)
	}
}

// TestProperty13_VariantCapBoundary checks the per-variant cap is the exact
// boundary (≤4 accepted, 5+ rejected) holding the product-total cap slack.
//
// Validates: Requirements 12.1, 12.5, 12.6.
func TestProperty13_VariantCapBoundary(t *testing.T) {
	property := func(cv, inc int) bool {
		currentVariantPhotos := nonNeg(cv) % (maxVariantPhotos + 1) // 0..4
		incoming := nonNeg(inc) % (maxVariantPhotos + 2)            // 0..5

		// No default-set or other-variant photos, so the product-total cap (20)
		// cannot bind here: this isolates the per-variant cap (4).
		err := checkPhotoLimits(currentVariantPhotos, 0, 0, incoming)
		accepted := err == nil
		shouldAccept := currentVariantPhotos+incoming <= maxVariantPhotos
		return accepted == shouldAccept
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 500}); err != nil {
		t.Errorf("variant-cap boundary property failed: %v", err)
	}
}

// TestProperty13_ProductTotalCapBoundary checks the product-total cap (20) binds
// exactly, even when the per-variant cap is satisfied.
//
// Validates: Requirements 12.3, 12.5, 12.6.
func TestProperty13_ProductTotalCapBoundary(t *testing.T) {
	property := func(ds, ov int) bool {
		defaultSetCount := nonNeg(ds)
		otherVariantsTotal := nonNeg(ov)

		// Keep the target variant within its own cap (current=0, incoming=1) so
		// only the product-total cap can cause a rejection.
		const currentVariantPhotos = 0
		const incoming = 1

		err := checkPhotoLimits(currentVariantPhotos, defaultSetCount, otherVariantsTotal, incoming)
		accepted := err == nil
		total := defaultSetCount + otherVariantsTotal + currentVariantPhotos + incoming
		shouldAccept := total <= maxProductPhotos
		return accepted == shouldAccept
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 500}); err != nil {
		t.Errorf("product-total cap boundary property failed: %v", err)
	}
}

// TestCheckPhotoLimits_Examples documents concrete accept/reject cases that pin
// the exact boundaries, complementing the randomized properties above.
func TestCheckPhotoLimits_Examples(t *testing.T) {
	cases := []struct {
		name                                         string
		current, defaultSet, otherVariants, incoming int
		wantErr                                      bool
	}{
		{"empty add one", 0, 0, 0, 1, false},
		{"variant exactly at cap", 0, 0, 0, 4, false},
		{"variant one over cap", 0, 0, 0, 5, true},
		{"variant fill from three", 3, 0, 0, 1, false},
		{"variant over from three", 3, 0, 0, 2, true},
		{"product exactly at total cap", 0, 6, 13, 1, false}, // 6+13+0+1 = 20
		{"product one over total cap", 0, 6, 14, 1, true},    // 6+14+0+1 = 21
		{"both caps ok", 2, 4, 4, 2, false},                  // variant 4≤4, total 12≤20
		{"variant cap binds before product", 4, 0, 0, 1, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := checkPhotoLimits(tc.current, tc.defaultSet, tc.otherVariants, tc.incoming)
			if (err != nil) != tc.wantErr {
				t.Errorf("checkPhotoLimits(%d,%d,%d,%d) err=%v, wantErr=%v",
					tc.current, tc.defaultSet, tc.otherVariants, tc.incoming, err, tc.wantErr)
			}
		})
	}
}
