import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANG_KEY = 'app_language';
const LANG_CHOSEN_KEY = 'app_language_chosen';

const translations = {
  ru: {
    home: 'Главная',
    cart: 'Корзина',
    favorites: 'Избранное',
    profile: 'Профиль',
    tagline: 'Всё, что нужно — рядом',
    login: 'Войти',
    register: 'Регистрация',
    loginTitle: 'Вход в аккаунт',
    registerTitle: 'Создать аккаунт',
    phoneNumber: 'Номер телефона',
    password: 'Пароль',
    enterPassword: 'Введите пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    yourFirstName: 'Ваше имя',
    yourLastName: 'Ваша фамилия',
    minChars: 'Минимум 6 символов',
    confirmPassword: 'Повторите пароль',
    repeatPassword: 'Повторите пароль',
    passwordMismatch: 'Пароли не совпадают',
    noAccount: 'Нет аккаунта?',
    createAccount: 'Зарегистрироваться',
    haveAccount: 'Уже есть аккаунт?',
    signIn: 'Войти',
    terms: 'Продолжая, вы соглашаетесь с',
    termsLink: 'условиями сервиса',
    userNotFound: 'Не найден',
    userNotRegistered: 'Пользователь не зарегистрирован. Создайте аккаунт.',
    error: 'Ошибка',
    loginError: 'Ошибка входа',
    registerError: 'Не удалось создать аккаунт',
    cancel: 'Отмена',
    profileTitle: 'Профиль',
    defaultUser: 'Пользователь',
    myOrders: 'Мои заказы',
    deliveryAddresses: 'Адреса доставки',
    paymentMethods: 'Способы оплаты',
    notifications: 'Уведомления',
    support: 'Поддержка',
    settings: 'Настройки',
    language: 'Язык',
    darkTheme: 'Тёмная тема',
    lightTheme: 'Светлая тема',
    logout: 'Выйти из аккаунта',
    logoutConfirmTitle: 'Выйти из аккаунта',
    logoutConfirmMsg: 'Вы уверены, что хотите выйти?',
    logoutBtn: 'Выйти',
    version: 'Версия',
    comingSoon: 'Скоро',
    inDevelopment: 'Функция в разработке',
    supportContact: 'Свяжитесь с нами:\ninfo@axentis.uz',
    noGalleryAccess: 'Нет доступа',
    allowGallery: 'Разрешите доступ к фотогалерее в настройках',
    uploadError: 'Ошибка',
    uploadFail: 'Не удалось загрузить фото',
    catalogTitle: 'Каталог',
    allProducts: 'Все товары',
    searchPlaceholder: 'Поиск товаров',
    notFound: 'Товары не найдены',
    noProducts: 'Нет товаров',
    cartTitle: 'Корзина',
    clearCart: 'Удалить все товары',
    clearCartMsg: 'Все товары будут удалены из корзины. Продолжить?',
    clear: 'Да, удалить',
    no: 'Нет',
    checkout: 'Оформить заказ',
    total: 'Итого',
    emptyCart: 'Корзина пуста',
    emptyCartHint: 'Добавьте товары из каталога',
    sum: 'сум',
    favoritesTitle: 'Избранное',
    items: 'товаров',
    listEmpty: 'Список пуст',
    favoritesHint: 'Нажмите на сердечко на карточке товара, чтобы сохранить его здесь',
    goToHome: 'Перейти в каталог',
    ordersTitle: 'Мои заказы',
    noOrders: 'Заказов нет',
    noOrdersHint: 'Оформите первый заказ',
    langSelectTitle: 'Выберите язык',
    langSelectSubtitle: 'Вы сможете изменить его позже в профиле',
    russian: 'Русский',
    uzbek: "O'zbek",
    continueBtn: 'Продолжить',
    currentLanguage: 'Текущий язык',

    // ─── Orders ──────────────────────────────────────────────
    orderLabel: 'Заказ',
    orderFrom: 'Заказ от',
    tabAll: 'Все',
    tabActive: 'Активные',
    tabDelivered: 'Доставленные',
    tabCancelled: 'Отменённые',
    statusPending: 'Ожидает',
    statusPendingFull: 'Ожидает подтверждения',
    statusConfirmed: 'Подтверждён',
    statusProcessing: 'Обрабатывается',
    statusShipped: 'В пути',
    statusDelivered: 'Доставлен',
    statusCancelled: 'Отменён',
    stepPlaced: 'Оформлен',
    stepConfirmed: 'Подтверждён',
    stepInTransit: 'В пути',
    stepDelivered: 'Доставлен',
    deliveryTitle: 'Доставка',
    byCourier: 'Курьером',
    pickup: 'Самовывоз',
    deliveryWord: 'Доставка',
    productsTitle: 'Товары',
    pcs: 'шт.',
    paymentTitle: 'Оплата',
    paymentCash: 'Наличными',
    paymentCard: 'Карта',
    recipient: 'Получатель',
    colorLabel: 'Цвет',
    sizeLabel: 'Размер',
    errorLoadOrders: 'Не удалось загрузить заказы',
    errorLoading: 'Ошибка загрузки',
    retry: 'Повторить',
    noOrdersInCategory: 'Нет заказов в этой категории',
    neverOrdered: 'Вы ещё не делали заказов',
    orderNotFound: 'Заказ не найден',
    // Returns
    returnTitle: 'Оформить возврат',
    returnPossibleWithin: 'Возврат возможен в течение',
    hoursShort: 'ч',
    afterOrder: 'после заказа',
    returnReasonPlaceholder: 'Опишите причину возврата...',
    sendRequest: 'Отправить заявку',
    sending: 'Отправка...',
    returnRequestedMsg: 'Заявка на возврат отправлена продавцу',
    returnExpired: 'Срок возврата истёк',
    returnWord: 'Возврат',
    describeReturnReason: 'Опишите причину возврата',
    returnSentMsg: 'Заявка на возврат отправлена продавцу. Ожидайте решения.',
    returnFailMsg: 'Не удалось отправить заявку на возврат. Попробуйте позже.',
    noReturnsAccepted: 'Эта компания не принимает возвраты',
    contactSupport: 'Связаться с поддержкой',
    supportTitle: 'Поддержка',
    supportPhoneMsg: 'Свяжитесь с нами по телефону',

    // ─── ProductCard ─────────────────────────────────────────
    sold: 'продано',
    priceFrom: 'от',

    // ─── Notifications ───────────────────────────────────────
    markAllRead: 'Прочитать все',
    noNotifications: 'Нет уведомлений',
    notificationsHint: 'Здесь будут появляться уведомления о заказах и акциях',

    // ─── Product questions ───────────────────────────────────
    questionsTitle: 'Вопросы о товаре',
    askQuestionBtn: 'Задать вопрос о товаре',
    askPlaceholder: 'Задайте вопрос продавцу...',
    loginToAskPlaceholder: 'Войдите, чтобы задать вопрос',
    noQuestionsYet: 'Пока нет вопросов. Задайте первый!',
    questionWord: 'Вопрос',
    enterQuestion: 'Введите текст вопроса',
    loginWord: 'Вход',
    loginToAskMsg: 'Войдите в аккаунт, чтобы задать вопрос',
    thanksWord: 'Спасибо!',
    questionSentMsg: 'Ваш вопрос отправлен продавцу. Ответ появится здесь.',

    // ─── Catalog ─────────────────────────────────────────────
    searchProductsBrands: 'Поиск товаров, брендов…',
    categoriesHere: 'Категории появятся здесь',
    sortPopular: 'Популярное',
    sortNew: 'Новинки',
    sortCheaper: 'Дешевле',
    sortExpensive: 'Дороже',
    noProductsInCategory: 'В этой категории пока нет товаров',

    // ─── Cart ────────────────────────────────────────────────
    notEnoughStock: 'Недостаточно товара',
    inStockOnlyPrefix: 'На складе доступно только',
    inStockOnlySuffix: 'шт.',
    productWord: 'Товар',
    atCheckout: 'при оформлении',

    // ─── Checkout ────────────────────────────────────────────
    stepDelivery: 'Доставка',
    stepPayment: 'Оплата',
    stepConfirm: 'Подтверждение',
    checkoutTitle: 'Оформление заказа',
    deliveryAddressTitle: 'Адрес доставки',
    orderComment: 'Комментарий к заказу',
    paymentMethodTitle: 'Способ оплаты',
    bankCard: 'Банковская карта',
    cashOnDelivery: 'Наличными при получении',
    selectCard: 'Выберите карту',
    mainCard: 'Основная',
    addNewCard: 'Добавить новую карту',
    cardData: 'Данные карты',
    saveCard: 'Сохранить карту',
    cardSaved: 'Карта сохранена',
    yourOrder: 'Ваш заказ',
    addressNotSet: 'Адрес не указан',
    free: 'Бесплатно',
    courierDeliveryFree: 'Курьерская доставка · Бесплатно',
    changePlaceOnMap: 'Изменить место на карте',
    selectPlaceOnMap: 'Выбрать место на карте',
    placeSelectedOnMap: 'Точка на карте выбрана',
    payAction: 'Оплатить',
    specifyDeliveryAddress: 'Укажите адрес доставки',
    enterFullCardNumber: 'Введите полный 16-значный номер карты',
    enterExpiry: 'Введите срок в формате ММ/ГГ',
    enterCardHolder: 'Введите имя держателя карты',
    cardAddFailed: 'Не удалось добавить карту',
    orderFailed: 'Не удалось оформить заказ. Попробуйте позже.',
    addressPlaceholder: 'ул. Ленина, 10, кв. 25',
    recipientNamePlaceholder: 'Имя получателя',
    commentPlaceholder: 'Например: оставить у двери',
    expiryPlaceholder: 'ММ/ГГ',
    holderNamePlaceholder: 'Имя Фамилия',
    byDefaultAddr: 'По умолчанию',
    savedAddress: 'Сохранённый адрес',
    frequentPlace: 'Частое место',
    ordersShort: 'зак.',

    // ─── Product detail ──────────────────────────────────────
    selectVariant: 'Выберите вариант',
    selectColorSize: 'Выберите цвет и размер',
    selectSize: 'Выберите размер',
    addToCartFail: 'Не удалось добавить в корзину',
    emptyReviewError: 'Нельзя отправить пустой отзыв',
    limitTitle: 'Ограничение',
    reviewLimitMsg: 'Вы уже оставили максимальное количество отзывов (2) для этого товара',
    reviewAdded: 'Ваш отзыв добавлен',
    reviewSendFail: 'Не удалось отправить отзыв',
    productNotFound: 'Товар не найден',
    reviewsWord: 'отзывов',
    noReviewsShort: 'Нет отзывов',
    memoryLabel: 'Память',
    outOfStockShort: 'нет',
    outOfStock: 'нет в наличии',
    deliveryAvailable: 'Доставка доступна',
    deliveryByCourierAddr: 'Курьером по вашему адресу',
    aboutProduct: 'О товаре',
    categoryLabel: 'Категория',
    generalCategory: 'Общее',
    skuLabel: 'Артикул',
    availableLabel: 'Доступно',
    collapse: 'Свернуть',
    readFull: 'Читать полностью',
    seller: 'Продавец',
    storeWord: 'Магазин',
    enableLocationForRegion: 'Включите геолокацию, чтобы видеть товары в вашем регионе',
    enableLocationBtn: 'Включить геолокацию',
    detectingRegion: 'Определяем ваш регион…',
    regionUndetected: 'Не удалось определить ваш регион. Включите геолокацию и попробуйте снова.',
    noPartnersInRegion: 'В вашем регионе пока нет наших партнёров',
    ratingsWord: 'оценок',
    goToStore: 'Перейти в магазин',
    allSellerProducts: 'Все товары продавца',
    leaveReview: 'Оставить отзыв',
    reviewHelps: 'Ваш отзыв поможет другим покупателям сделать правильный выбор',
    yourRating: 'Ваша оценка',
    ratingPoor: 'Плохо',
    ratingFair: 'Так себе',
    ratingOk: 'Нормально',
    ratingGood: 'Хорошо',
    ratingExcellent: 'Отлично',
    selectRating: 'Выберите оценку',
    commentLabel: 'Комментарий',
    optional: 'Необязательно',
    reviewPlaceholder: 'Поделитесь своими впечатлениями о товаре, качестве, доставке или обслуживании продавца…',
    tipPolite: 'Будьте вежливы',
    tipOnTopic: 'Пишите по теме',
    tipHelpOthers: 'Помогите другим',
    submitReviewBtn: 'Отправить отзыв',
    reviewsTitle: 'Отзывы',
    noReviewsBeFirst: 'Нет отзывов. Будьте первым!',
    buyer: 'Покупатель',
    sellerAnswer: 'Ответ продавца',
    awaitingSellerAnswer: 'Ожидает ответа продавца',
    boughtWith: 'С этим товаром покупают',
    similarProducts: 'Похожие товары',
    toWord: 'до',
    buyNow: 'Купить сейчас',

    // ─── Company store ───────────────────────────────────────
    authRequired: 'Требуется авторизация',
    loginToReview: 'Войдите в аккаунт, чтобы оставить отзыв',
    storeReviewSaved: 'Ваш отзыв о магазине сохранён',
    loginToSubscribe: 'Войдите в аккаунт чтобы подписаться',
    tryLater: 'Попробуйте позже',
    storeVerified: 'Магазин подтверждён',
    storeRating: 'Рейтинг\nмагазина',
    productsWord: 'товаров',
    subscribersWord: 'подписчиков',
    positiveReviewsWord: 'положительных отзывов',
    subscribed: 'Подписан',
    subscribe: 'Подписаться',
    aboutStore: 'О магазине',
    storeReviewsTab: 'Отзывы магазина',
    descNotAdded: 'Описание пока не добавлено.',
    productsInCatalog: 'товаров в каталоге',
    storeRatingLine: 'Рейтинг магазина:',
    storeReviewsTitle: 'Отзывы о магазине',
    rateStore: 'Оцените магазин',
    storeReviewPlaceholder: 'Поделитесь своими впечатлениями о магазине…',
    tipQuality: 'Качество товара',
    tipDeliverySpeed: 'Скорость доставки',
    tipService: 'Обслуживание',
    tipPrices: 'Цены',

    // ─── Order confirmed ─────────────────────────────────────
    orderPlaced: 'Заказ оформлен',
    orderAcceptedThanks: 'Спасибо! Ваш заказ принят',
    toHome: 'На главную',

    // ─── Home / Search ───────────────────────────────────────
    popularProducts: 'Популярные товары',
    searchResults: 'Результаты поиска',
    welcome: 'Добро пожаловать',
    nothingFound: 'Ничего не найдено',
    noProductsAvailable: 'Нет доступных товаров',
    popularQueries: 'Популярные запросы',
    byQuery: 'По запросу',
    notFoundProducts: 'товаров не найдено',
    foundLabel: 'Найдено:',

    // ─── Banner ──────────────────────────────────────────────
    bannerSaleTitle: 'Скидки до 50%',
    bannerSaleSub: 'На электронику и гаджеты',
    bannerNewTitle: 'Новые поступления',
    bannerNewSub: 'Свежие товары каждый день',
    bannerDeliveryTitle: 'Быстрая доставка',
    bannerDeliverySub: 'По всему Узбекистану',
    linkOpenFail: 'Не удалось открыть ссылку',

    // ─── Login ───────────────────────────────────────────────
    noServerConnection: 'Нет связи с сервером',
    connectFailMsg: 'Не удалось подключиться к axentis.uz. Проверьте интернет или попробуйте позже.',
    invalidData: 'Неверные данные',
    invalidPhoneOrPass: 'Неверный телефон или пароль',
    passwordTooShort: 'Пароль должен быть не менее 6 символов',

    // ─── Payment cards ───────────────────────────────────────
    enterCardNumber16: 'Введите полный 16-значный номер карты',
    enterExpiryMMYY: 'Введите срок в формате ММ/ГГ',
    enterCardHolderName: 'Введите имя держателя карты',
    cardAddFail: 'Не удалось добавить карту',
    deleteCard: 'Удалить карту',
    deleteCardQ: 'Удалить карту ****',
    deleteWord: 'Удалить',
    cardDeleteFail: 'Не удалось удалить карту',
    setDefaultCardFail: 'Не удалось установить карту по умолчанию',
    noCards: 'Нет добавленных карт',
    mainBadge: 'Основная',
    cardHolder: 'Держатель',
    expiryShort: 'Срок',
    addCardBtn: 'Добавить карту',
    newCard: 'Новая карта',
    cardTypeLabel: 'Тип карты',
    cardNumberLabel: 'Номер карты',
    expiryDateLabel: 'Срок действия',
    holderNameLabel: 'Имя держателя',
    saveWord: 'Сохранить',

    // ─── Delivery addresses ──────────────────────────────────
    deleteAddressQ: 'Удалить адрес?',
    irreversibleAction: 'Это действие необратимо.',
    addressDeleteFail: 'Не удалось удалить адрес.',
    setDefaultAddrFail: 'Не удалось установить адрес по умолчанию.',
    noSavedAddresses: 'Нет сохранённых адресов',
    addAddressHint: 'Добавьте адрес доставки, чтобы быстро оформлять заказы',
    addAddressBtn: 'Добавить адрес',

    // ─── Map location picker ─────────────────────────────────
    noAccessTitle: 'Нет доступа',
    allowGeo: 'Разрешите доступ к геолокации в настройках устройства.',
    geoFail: 'Не удалось получить геолокацию.',
    notFoundTitle: 'Не найдено',
    nothingFoundQuery: 'По вашему запросу ничего не найдено.',
    searchFail: 'Не удалось выполнить поиск.',
    newAddress: 'Новый адрес',
    selectDeliveryPlace: 'Выберите место доставки',
    searchAddressPh: 'Поиск адреса',
    selectedPoint: 'Выбранная точка',
    moveMapHint: 'Передвигайте карту или маркер, чтобы выбрать точное место',
    selectThisPlace: 'Выбрать это место',

    // ─── Catalog filters ─────────────────────────────────────
    filters: 'Фильтры',
    priceFromLabel: 'Цена от',
    priceToLabel: 'Цена до',
    onlyInStock: 'Только в наличии',
    applyBtn: 'Применить',
    resetBtn: 'Сбросить',
    addPhotoBtn: 'Добавить фото',
    withPhoto: 'С фото',
    recentlyViewed: 'Вы недавно смотрели',
    recommendedForYou: 'Рекомендуем вам',
  },
  uz: {
    home: 'Bosh sahifa',
    cart: 'Savat',
    favorites: 'Sevimlilar',
    profile: 'Profil',
    tagline: 'Kerakli narsa — yaqin atrofda',
    login: 'Kirish',
    register: "Ro'yxatdan o'tish",
    loginTitle: 'Hisobga kirish',
    registerTitle: 'Hisob yaratish',
    phoneNumber: 'Telefon raqami',
    password: 'Parol',
    enterPassword: 'Parolni kiriting',
    firstName: 'Ism',
    lastName: 'Familiya',
    yourFirstName: 'Ismingiz',
    yourLastName: 'Familiyangiz',
    minChars: 'Kamida 6 ta belgi',
    confirmPassword: 'Parolni tasdiqlang',
    repeatPassword: 'Parolni takrorlang',
    passwordMismatch: 'Parollar mos kelmadi',
    noAccount: "Hisob yo'qmi?",
    createAccount: "Ro'yxatdan o'tish",
    haveAccount: 'Hisob bormi?',
    signIn: 'Kirish',
    terms: 'Davom etib, siz',
    termsLink: 'xizmat shartlariga rozilik bildirasiz',
    userNotFound: 'Topilmadi',
    userNotRegistered: "Foydalanuvchi ro'yxatdan o'tmagan. Hisob yarating.",
    error: 'Xato',
    loginError: 'Kirish xatosi',
    registerError: 'Hisob yaratolmadi',
    cancel: 'Bekor qilish',
    profileTitle: 'Profil',
    defaultUser: 'Foydalanuvchi',
    myOrders: 'Buyurtmalarim',
    deliveryAddresses: 'Yetkazib berish manzillari',
    paymentMethods: "To'lov usullari",
    notifications: 'Bildirishnomalar',
    support: "Qo'llab-quvvatlash",
    settings: 'Sozlamalar',
    language: 'Til',
    darkTheme: "Qorong'i mavzu",
    lightTheme: "Yorug' mavzu",
    logout: 'Hisobdan chiqish',
    logoutConfirmTitle: 'Hisobdan chiqish',
    logoutConfirmMsg: 'Chiqishni xohlaysizmi?',
    logoutBtn: 'Chiqish',
    version: 'Versiya',
    comingSoon: 'Tez kunda',
    inDevelopment: 'Funksiya ishlab chiqilmoqda',
    supportContact: "Biz bilan bog'laning:\ninfo@axentis.uz",
    noGalleryAccess: "Ruxsat yo'q",
    allowGallery: 'Sozlamalarda foto galereyaga ruxsat bering',
    uploadError: 'Xato',
    uploadFail: "Fotoni yuklab bo'lmadi",
    catalogTitle: 'Katalog',
    allProducts: 'Barcha mahsulotlar',
    searchPlaceholder: 'Mahsulot qidirish',
    notFound: 'Mahsulotlar topilmadi',
    noProducts: "Mahsulotlar yo'q",
    cartTitle: 'Savat',
    clearCart: "Barcha mahsulotlarni o'chirish",
    clearCartMsg: "Barcha mahsulotlar savatdan o'chiriladi. Davom etasizmi?",
    clear: "Ha, o'chirish",
    no: "Yo'q",
    checkout: 'Buyurtma berish',
    total: 'Jami',
    emptyCart: "Savat bo'sh",
    emptyCartHint: "Katalogdan mahsulot qo'shing",
    sum: "so'm",
    favoritesTitle: 'Sevimlilar',
    items: 'ta mahsulot',
    listEmpty: "Ro'yxat bo'sh",
    favoritesHint: 'Mahsulot kartasidagi yurakchani bosing va uni bu yerda saqlang',
    goToHome: "Katalogga o'tish",
    ordersTitle: 'Buyurtmalarim',
    noOrders: "Buyurtmalar yo'q",
    noOrdersHint: 'Birinchi buyurtmangizni bering',
    langSelectTitle: 'Tilni tanlang',
    langSelectSubtitle: "Keyinchalik profildan o'zgartirish mumkin",
    russian: 'Русский',
    uzbek: "O'zbek",
    continueBtn: 'Davom etish',
    currentLanguage: 'Joriy til',

    // ─── Orders ──────────────────────────────────────────────
    orderLabel: 'Buyurtma',
    orderFrom: 'Buyurtma sanasi',
    tabAll: 'Barchasi',
    tabActive: 'Faol',
    tabDelivered: 'Yetkazilgan',
    tabCancelled: 'Bekor qilingan',
    statusPending: 'Kutilmoqda',
    statusPendingFull: 'Tasdiqlash kutilmoqda',
    statusConfirmed: 'Tasdiqlandi',
    statusProcessing: 'Tayyorlanmoqda',
    statusShipped: "Yo'lda",
    statusDelivered: 'Yetkazildi',
    statusCancelled: 'Bekor qilindi',
    stepPlaced: 'Rasmiylashtirildi',
    stepConfirmed: 'Tasdiqlandi',
    stepInTransit: "Yo'lda",
    stepDelivered: 'Yetkazildi',
    deliveryTitle: 'Yetkazib berish',
    byCourier: 'Kuryer orqali',
    pickup: "O'zi olib ketish",
    deliveryWord: 'Yetkazib berish',
    productsTitle: 'Mahsulotlar',
    pcs: 'dona',
    paymentTitle: "To'lov",
    paymentCash: 'Naqd pul',
    paymentCard: 'Karta',
    recipient: 'Qabul qiluvchi',
    colorLabel: 'Rang',
    sizeLabel: "O'lcham",
    errorLoadOrders: "Buyurtmalarni yuklab bo'lmadi",
    errorLoading: 'Yuklashda xato',
    retry: 'Qayta urinish',
    noOrdersInCategory: "Bu turkumda buyurtmalar yo'q",
    neverOrdered: 'Siz hali buyurtma bermagansiz',
    orderNotFound: 'Buyurtma topilmadi',
    // Returns
    returnTitle: 'Qaytarishni rasmiylashtirish',
    returnPossibleWithin: 'Qaytarish mumkin:',
    hoursShort: 'soat',
    afterOrder: 'buyurtmadan keyin',
    returnReasonPlaceholder: 'Qaytarish sababini yozing...',
    sendRequest: "So'rov yuborish",
    sending: 'Yuborilmoqda...',
    returnRequestedMsg: "Qaytarish so'rovi sotuvchiga yuborildi",
    returnExpired: 'Qaytarish muddati tugadi',
    returnWord: 'Qaytarish',
    describeReturnReason: 'Qaytarish sababini yozing',
    returnSentMsg: "Qaytarish so'rovi sotuvchiga yuborildi. Javobni kuting.",
    returnFailMsg: "So'rovni yuborib bo'lmadi. Keyinroq urinib ko'ring.",
    noReturnsAccepted: 'Bu kompaniya qaytarishni qabul qilmaydi',
    contactSupport: "Qo'llab-quvvatlash bilan bog'lanish",
    supportTitle: "Qo'llab-quvvatlash",
    supportPhoneMsg: "Biz bilan telefon orqali bog'laning",

    // ─── ProductCard ─────────────────────────────────────────
    sold: 'sotildi',
    priceFrom: 'dan',

    // ─── Notifications ───────────────────────────────────────
    markAllRead: "Hammasini o'qish",
    noNotifications: "Bildirishnomalar yo'q",
    notificationsHint: "Bu yerda buyurtmalar va aksiyalar haqida bildirishnomalar paydo bo'ladi",

    // ─── Product questions ───────────────────────────────────
    questionsTitle: 'Mahsulot haqida savollar',
    askQuestionBtn: 'Mahsulot haqida savol berish',
    askPlaceholder: 'Sotuvchiga savol bering...',
    loginToAskPlaceholder: 'Savol berish uchun tizimga kiring',
    noQuestionsYet: "Hozircha savollar yo'q. Birinchi bo'lib so'rang!",
    questionWord: 'Savol',
    enterQuestion: 'Savol matnini kiriting',
    loginWord: 'Kirish',
    loginToAskMsg: 'Savol berish uchun hisobingizga kiring',
    thanksWord: 'Rahmat!',
    questionSentMsg: "Savolingiz sotuvchiga yuborildi. Javob shu yerda paydo bo'ladi.",

    // ─── Catalog ─────────────────────────────────────────────
    searchProductsBrands: 'Mahsulot, brendlarni qidirish…',
    categoriesHere: "Turkumlar shu yerda paydo bo'ladi",
    sortPopular: 'Ommabop',
    sortNew: 'Yangiliklar',
    sortCheaper: 'Arzonroq',
    sortExpensive: 'Qimmatroq',
    noProductsInCategory: "Bu turkumda hozircha mahsulot yo'q",

    // ─── Cart ────────────────────────────────────────────────
    notEnoughStock: 'Mahsulot yetarli emas',
    inStockOnlyPrefix: 'Omborda faqat',
    inStockOnlySuffix: 'dona mavjud',
    productWord: 'Mahsulot',
    atCheckout: 'rasmiylashtirishda',

    // ─── Checkout ────────────────────────────────────────────
    stepDelivery: 'Yetkazib berish',
    stepPayment: "To'lov",
    stepConfirm: 'Tasdiqlash',
    checkoutTitle: 'Buyurtmani rasmiylashtirish',
    deliveryAddressTitle: 'Yetkazib berish manzili',
    orderComment: 'Buyurtmaga izoh',
    paymentMethodTitle: "To'lov usuli",
    bankCard: 'Bank kartasi',
    cashOnDelivery: 'Qabul qilishda naqd pul',
    selectCard: 'Kartani tanlang',
    mainCard: 'Asosiy',
    addNewCard: "Yangi karta qo'shish",
    cardData: "Karta ma'lumotlari",
    saveCard: 'Kartani saqlash',
    cardSaved: 'Karta saqlandi',
    yourOrder: 'Sizning buyurtmangiz',
    addressNotSet: "Manzil ko'rsatilmagan",
    free: 'Bepul',
    courierDeliveryFree: 'Kuryer yetkazib berish · Bepul',
    changePlaceOnMap: "Xaritada joyni o'zgartirish",
    selectPlaceOnMap: 'Xaritadan joyni tanlash',
    placeSelectedOnMap: 'Xaritada nuqta tanlandi',
    payAction: "To'lash",
    specifyDeliveryAddress: 'Yetkazib berish manzilini kiriting',
    enterFullCardNumber: "Kartaning to'liq 16 raqamini kiriting",
    enterExpiry: 'Muddatni OO/YY formatida kiriting',
    enterCardHolder: 'Karta egasining ismini kiriting',
    cardAddFailed: "Kartani qo'shib bo'lmadi",
    orderFailed: "Buyurtmani rasmiylashtirib bo'lmadi. Keyinroq urinib ko'ring.",
    addressPlaceholder: "Manzil: ko'cha, uy, xonadon",
    recipientNamePlaceholder: 'Qabul qiluvchi ismi',
    commentPlaceholder: 'Masalan: eshik oldida qoldiring',
    expiryPlaceholder: 'OO/YY',
    holderNamePlaceholder: 'Ism Familiya',
    byDefaultAddr: 'Standart',
    savedAddress: 'Saqlangan manzil',
    frequentPlace: 'Tez-tez joy',
    ordersShort: 'buyurtma',

    // ─── Product detail ──────────────────────────────────────
    selectVariant: 'Variantni tanlang',
    selectColorSize: "Rang va o'lchamni tanlang",
    selectSize: "O'lchamni tanlang",
    addToCartFail: "Savatga qo'shib bo'lmadi",
    emptyReviewError: "Bo'sh sharh yuborib bo'lmaydi",
    limitTitle: 'Cheklov',
    reviewLimitMsg: "Siz bu mahsulot uchun sharhlarning maksimal sonini (2) qoldirib bo'ldingiz",
    reviewAdded: "Sharhingiz qo'shildi",
    reviewSendFail: "Sharh yuborib bo'lmadi",
    productNotFound: 'Mahsulot topilmadi',
    reviewsWord: 'sharh',
    noReviewsShort: "Sharhlar yo'q",
    memoryLabel: 'Xotira',
    outOfStockShort: "yo'q",
    outOfStock: 'mavjud emas',
    deliveryAvailable: 'Yetkazib berish mavjud',
    deliveryByCourierAddr: 'Manzilingizga kuryer orqali',
    aboutProduct: 'Mahsulot haqida',
    categoryLabel: 'Kategoriya',
    generalCategory: 'Umumiy',
    skuLabel: 'Artikul',
    availableLabel: 'Mavjud',
    collapse: "Yig'ish",
    readFull: "To'liq o'qish",
    seller: 'Sotuvchi',
    storeWord: "Do'kon",
    enableLocationForRegion: 'Hududingizdagi mahsulotlarni koʻrish uchun geolokatsiyani yoqing',
    enableLocationBtn: 'Geolokatsiyani yoqish',
    detectingRegion: 'Hududingiz aniqlanmoqda…',
    regionUndetected: 'Hududingizni aniqlab boʻlmadi. Geolokatsiyani yoqib, qayta urinib koʻring.',
    noPartnersInRegion: 'Hududingizda hozircha hamkorlarimiz yoʻq',
    ratingsWord: 'baho',
    goToStore: "Do'konga o'tish",
    allSellerProducts: 'Sotuvchining barcha mahsulotlari',
    leaveReview: 'Sharh qoldirish',
    reviewHelps: "Sharhingiz boshqa xaridorlarga to'g'ri tanlov qilishga yordam beradi",
    yourRating: 'Sizning bahoyingiz',
    ratingPoor: 'Yomon',
    ratingFair: "O'rtacha",
    ratingOk: 'Qoniqarli',
    ratingGood: 'Yaxshi',
    ratingExcellent: "A'lo",
    selectRating: 'Bahoni tanlang',
    commentLabel: 'Izoh',
    optional: 'Majburiy emas',
    reviewPlaceholder: "Mahsulot, sifat, yetkazib berish yoki sotuvchi xizmati haqidagi taassurotlaringizni ulashing…",
    tipPolite: "Xushmuomala bo'ling",
    tipOnTopic: "Mavzu bo'yicha yozing",
    tipHelpOthers: 'Boshqalarga yordam bering',
    submitReviewBtn: 'Sharh yuborish',
    reviewsTitle: 'Sharhlar',
    noReviewsBeFirst: "Sharhlar yo'q. Birinchi bo'ling!",
    buyer: 'Xaridor',
    sellerAnswer: 'Sotuvchining javobi',
    awaitingSellerAnswer: 'Sotuvchining javobini kutmoqda',
    boughtWith: 'Bu mahsulot bilan birga olishadi',
    similarProducts: "O'xshash mahsulotlar",
    toWord: 'gacha',
    buyNow: 'Hozir sotib olish',

    // ─── Company store ───────────────────────────────────────
    authRequired: 'Avtorizatsiya talab qilinadi',
    loginToReview: 'Sharh qoldirish uchun hisobingizga kiring',
    storeReviewSaved: "Do'kon haqidagi sharhingiz saqlandi",
    loginToSubscribe: "Obuna bo'lish uchun hisobingizga kiring",
    tryLater: "Keyinroq urinib ko'ring",
    storeVerified: "Do'kon tasdiqlangan",
    storeRating: "Do'kon\nreytingi",
    productsWord: 'mahsulot',
    subscribersWord: 'obunachi',
    positiveReviewsWord: 'ijobiy sharhlar',
    subscribed: "Obuna bo'lingan",
    subscribe: "Obuna bo'lish",
    aboutStore: "Do'kon haqida",
    storeReviewsTab: "Do'kon sharhlari",
    descNotAdded: "Tavsif hali qo'shilmagan.",
    productsInCatalog: 'katalogdagi mahsulot',
    storeRatingLine: "Do'kon reytingi:",
    storeReviewsTitle: "Do'kon haqidagi sharhlar",
    rateStore: "Do'konni baholang",
    storeReviewPlaceholder: "Do'kon haqidagi taassurotlaringizni ulashing…",
    tipQuality: 'Mahsulot sifati',
    tipDeliverySpeed: 'Yetkazib berish tezligi',
    tipService: "Xizmat ko'rsatish",
    tipPrices: 'Narxlar',

    // ─── Order confirmed ─────────────────────────────────────
    orderPlaced: 'Buyurtma rasmiylashtirildi',
    orderAcceptedThanks: 'Rahmat! Buyurtmangiz qabul qilindi',
    toHome: 'Bosh sahifaga',

    // ─── Home / Search ───────────────────────────────────────
    popularProducts: 'Ommabop mahsulotlar',
    searchResults: 'Qidiruv natijalari',
    welcome: 'Xush kelibsiz',
    nothingFound: 'Hech narsa topilmadi',
    noProductsAvailable: "Mavjud mahsulotlar yo'q",
    popularQueries: "Ommabop so'rovlar",
    byQuery: "So'rov bo'yicha",
    notFoundProducts: 'mahsulot topilmadi',
    foundLabel: 'Topildi:',

    // ─── Banner ──────────────────────────────────────────────
    bannerSaleTitle: '50% gacha chegirma',
    bannerSaleSub: 'Elektronika va gadjetlarga',
    bannerNewTitle: 'Yangi mahsulotlar',
    bannerNewSub: 'Har kuni yangi mahsulotlar',
    bannerDeliveryTitle: 'Tez yetkazib berish',
    bannerDeliverySub: "Butun O'zbekiston bo'ylab",
    linkOpenFail: "Havolani ochib bo'lmadi",

    // ─── Login ───────────────────────────────────────────────
    noServerConnection: "Server bilan aloqa yo'q",
    connectFailMsg: "axentis.uz ga ulanib bo'lmadi. Internetni tekshiring yoki keyinroq urinib ko'ring.",
    invalidData: "Noto'g'ri ma'lumotlar",
    invalidPhoneOrPass: "Telefon yoki parol noto'g'ri",
    passwordTooShort: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",

    // ─── Payment cards ───────────────────────────────────────
    enterCardNumber16: "To'liq 16 raqamli karta raqamini kiriting",
    enterExpiryMMYY: 'Amal qilish muddatini OO/YY formatida kiriting',
    enterCardHolderName: 'Karta egasining ismini kiriting',
    cardAddFail: "Kartani qo'shib bo'lmadi",
    deleteCard: "Kartani o'chirish",
    deleteCardQ: "Kartani o'chirish ****",
    deleteWord: "O'chirish",
    cardDeleteFail: "Kartani o'chirib bo'lmadi",
    setDefaultCardFail: "Kartani standart qilib bo'lmadi",
    noCards: "Qo'shilgan kartalar yo'q",
    mainBadge: 'Asosiy',
    cardHolder: 'Egasi',
    expiryShort: 'Muddat',
    addCardBtn: "Karta qo'shish",
    newCard: 'Yangi karta',
    cardTypeLabel: 'Karta turi',
    cardNumberLabel: 'Karta raqami',
    expiryDateLabel: 'Amal qilish muddati',
    holderNameLabel: 'Egasining ismi',
    saveWord: 'Saqlash',

    // ─── Delivery addresses ──────────────────────────────────
    deleteAddressQ: "Manzilni o'chirasizmi?",
    irreversibleAction: "Bu amalni qaytarib bo'lmaydi.",
    addressDeleteFail: "Manzilni o'chirib bo'lmadi.",
    setDefaultAddrFail: "Manzilni standart qilib bo'lmadi.",
    noSavedAddresses: "Saqlangan manzillar yo'q",
    addAddressHint: "Buyurtmalarni tez rasmiylashtirish uchun manzil qo'shing",
    addAddressBtn: "Manzil qo'shish",

    // ─── Map location picker ─────────────────────────────────
    noAccessTitle: "Ruxsat yo'q",
    allowGeo: 'Qurilma sozlamalarida geolokatsiyaga ruxsat bering.',
    geoFail: "Geolokatsiyani aniqlab bo'lmadi.",
    notFoundTitle: 'Topilmadi',
    nothingFoundQuery: "So'rovingiz bo'yicha hech narsa topilmadi.",
    searchFail: "Qidiruvni amalga oshirib bo'lmadi.",
    newAddress: 'Yangi manzil',
    selectDeliveryPlace: 'Yetkazib berish joyini tanlang',
    searchAddressPh: 'Manzil qidirish',
    selectedPoint: 'Tanlangan nuqta',
    moveMapHint: "Aniq joyni tanlash uchun xarita yoki markerni suring",
    selectThisPlace: 'Shu joyni tanlash',

    // ─── Catalog filters ─────────────────────────────────────
    filters: 'Filtrlar',
    priceFromLabel: 'Narx (dan)',
    priceToLabel: 'Narx (gacha)',
    onlyInStock: 'Faqat mavjud',
    applyBtn: "Qo'llash",
    resetBtn: 'Tozalash',
    addPhotoBtn: "Foto qo'shish",
    withPhoto: 'Foto bilan',
    recentlyViewed: "Yaqinda ko'rganlaringiz",
    recommendedForYou: 'Sizga tavsiya etamiz',
  },
};

const LanguageContext = createContext({});

export const LanguageProvider = ({ children }) => {
  const [language, setLang] = useState('uz');
  const [hasChosenLanguage, setHasChosenLanguage] = useState(false);
  const [isLanguageLoading, setIsLanguageLoading] = useState(true);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const [saved, chosen] = await Promise.all([
        AsyncStorage.getItem(LANG_KEY),
        AsyncStorage.getItem(LANG_CHOSEN_KEY),
      ]);
      if (saved === 'ru' || saved === 'uz') setLang(saved);
      if (chosen === 'true') setHasChosenLanguage(true);
    } catch {
      // ignore
    } finally {
      setIsLanguageLoading(false);
    }
  };

  const setLanguage = async (lang) => {
    setLang(lang);
    try {
      await AsyncStorage.setItem(LANG_KEY, lang);
    } catch {}
  };

  const markLanguageChosen = async () => {
    setHasChosenLanguage(true);
    try {
      await AsyncStorage.setItem(LANG_CHOSEN_KEY, 'true');
    } catch {}
  };

  const t = (key) => {
    return translations[language]?.[key] ?? translations.ru?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, hasChosenLanguage, markLanguageChosen, isLanguageLoading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
