export { API_BASE_URL, UPLOADS_BASE_URL as UPLOADS_URL, SOCKET_URL } from '../config';

export const ENDPOINTS = {
  registerUser: '/auth/register/user',
  loginUser: '/auth/login/user',
  products: '/products',
  productDetail: (id: number) => `/products/${id}`,
  productReviews: (id: number) => `/products/${id}/reviews`,
  productReviewStats: (id: number) => `/products/${id}/review-stats`,
  productSimilar: (id: number) => `/products/${id}/similar`,
  companies: '/companies',
  companyDetail: (id: number) => `/companies/${id}`,
  nearestCompanies: '/companies/nearest',
  cart: (phone: string) => `/cart/${phone}`,
  cartCount: (phone: string) => `/cart/${phone}/count`,
  cartAdd: '/cart',
  cartSet: '/cart/set',
  cartDeleteItem: (id: number) => `/cart/item/${id}`,
  cartClear: (phone: string) => `/cart/user/${phone}`,
  favorites: (phone: string) => `/favorites/${phone}`,
  favoritesCount: (phone: string) => `/favorites/${phone}/count`,
  favoritesToggle: '/favorites/toggle',
  favoritesCheck: '/favorites/check',
  orders: '/orders',
  orderDetail: (id: number) => `/orders/${id}`,
  orderStatus: (id: number) => `/orders/${id}/status`,
  userProfile: (phone: string) => `/users/${phone}/profile`,
  userAvatar: (phone: string) => `/users/${phone}/avatar`,
  userDefaultAddress: (phone: string) => `/users/${phone}/default-delivery-address`,
  categories: '/categories',
  categoryProducts: '/categories/products',
  notifications: '/notifications',
  notificationsUnread: '/notifications/unread-count',
  notificationRead: (id: number) => `/notifications/${id}/read`,
  notificationsMarkAll: '/notifications/mark-all-read',
  pushToken: '/notifications/push-token',
  approvedDiscounts: '/discounts/approved',
  approvedAggressiveDiscounts: '/aggressive-discounts/approved',
  ads: '/ads',
  reviews: '/reviews',
  reviewVote: (id: number) => `/reviews/${id}/vote`,
  paymentCards: (phone: string) => `/payment-cards/${phone}`,
};
